version: '2'
services:
  iiwa-stack :
    image: ros-docker-base
    environment:
     # ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - $HOME/Volume/iiwa_stack:/root/catkin_ws/src/iiwa_stack
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null 

